scan_filter_chain:
- name: angle0
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle:  -1.5708
    upper_angle:  -0.7854
- name: angle1
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: 1.5708
    upper_angle: 2.3562

